includes = -I../include -I../include/renderer\
 -I../build/emscripten-deps\
 -I../build/emscripten-deps/boost/include\
 -I../build/emscripten-deps/ft2/include\
 -I../build/emscripten-deps/glm\
 -I../build/emscripten-deps/SDL2/include

CXXFLAGS = -std=c++1y -Wall -pipe -O2 -g -ffast-math -fno-rtti

LDFLAGS = -s USE_SDL=0\
 ../build/emscripten-deps/bytecode/libfreetype.a\
 ../build/emscripten-deps/bytecode/libphysfs.a\
 ../build/emscripten-deps/bytecode/libSDL2.a\
 --preload-file data --preload-file internal.zip

all: test.html

test.html: test.cpp ../engine.bc internal.zip test_state.h test_collision_state.h
	$(CXX) $(CXXFLAGS) $(includes) $< ../engine.bc -o $@$(SUFFIX) $(LDFLAGS)
	
internal.zip: ../build/internal.zip
	cp $< $@

clean:
	$(RM) test.html test.html.mem test.js
